<a href="https://colab.research.google.com/github/avseitsevad/Avseitseva_ZBPI212/blob/main/5%20%D1%81%D0%B5%D0%BC%D0%B5%D1%81%D1%82%D1%80/ML%20/%D0%9B%D0%A01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. С помощью массивов numpy создайте таблицу умножения

In [ ]:
x_multiply = np.arange(1, 10)
y_multiply = x_multiply[:, np.newaxis]
table = x_multiply * y_multiply
print(table)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


2. Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число), и разность (вещественное число) и создает матрицу numpy по диагонали, которой располагаются первые N членов арифметической прогрессии.


In [ ]:
def create_diagonal_matrix(n, first_elem, diff):
    progression = first_elem + diff * np.arange(n)
    return np.diag(progression)

print(create_diagonal_matrix(5, 0.2, 0.5))

[[0.2 0.  0.  0.  0. ]
 [0.  0.7 0.  0.  0. ]
 [0.  0.  1.2 0.  0. ]
 [0.  0.  0.  1.7 0. ]
 [0.  0.  0.  0.  2.2]]


3. Сгенерируйте средствами numpy матрицу А 5 на 5, содержащую последовательные числа от 1 до 25. Используя срезы извлеките в плоский массив все нечетные элементы этой матрицы.


In [ ]:
a = np.arange(1, 26).reshape(5, 5)
print(*a[0::2, 1::2].flatten())

2 4 12 14 22 24


4. Создайте двумерный массив, содержащий единицы на границе и нули внутри.

In [ ]:
n = 5
a = np.ones((n, n), dtype=int)
a[1:-1, 1:-1] = 0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


5. Создайте две матрицы размером (5,5). Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания, другая имеет треугольную форму содержащую 5 на основной диагонали и в позициях выше ее, а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы.


In [ ]:
a = np.ones((5,5), dtype=int)
a[1::2, ::2] = 0
a[::2, 1::2]= 0
print(a)

b = np.zeros((5,5), dtype=int)
b[np.triu_indices(5)] = 5
print(b)

det_a = np.linalg.det(a)
det_b = np.linalg.det(b)
print("det a = {}, det b = {}".format(det_a, det_b))

if det_a:
  inv_a = np.linalg.inv(a)
  print("inv a = {}".format(inv_a))
if det_b:
    inv_b = np.linalg.inv(b)
    print("inv b = \n {}".format(inv_b))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]
[[5 5 5 5 5]
 [0 5 5 5 5]
 [0 0 5 5 5]
 [0 0 0 5 5]
 [0 0 0 0 5]]
det a = 0.0, det b = 3124.999999999999
inv b = 
 [[ 0.2 -0.2  0.   0.   0. ]
 [ 0.   0.2 -0.2  0.   0. ]
 [ 0.   0.   0.2 -0.2  0. ]
 [ 0.   0.   0.   0.2 -0.2]
 [ 0.   0.   0.   0.   0.2]]


6. С помощью pandas загрузите датасет для предсказания цены квартиры, прилагающийся к этой работе.


In [ ]:
import pandas as pd
df = pd.read_csv('data.csv')

7. Выведите на экран несколько первых и несколько последний строк файла.


In [ ]:
print(df.head())
print(df.tail())

      Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   
1   3013          22    1.0   39.832524   23.169223            8.0      7   
2   8215           1    3.0   78.342215   47.671972           10.0      2   
3   2352           1    1.0   40.409907         NaN            1.0     10   
4  13866          94    2.0   64.285067   38.562517            9.0     16   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   
1         8.0       1966   0.118537         B         B        30      6207   
2        17.0       1988   0.025609         B         B        33      5261   
3        22.0       1977   0.007122         B         B         1       264   
4        16.0       1972   0.282798         B         B        33      8667   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2       

8. Выведите с помощью методов pandas основные количественные параметры датасета: количество строк и столбцов, тип данных каждого поля, количество значений в каждом столбце, шкала измерения каждого численного поля.


In [ ]:
print(f"Строк: {df.shape[0]}, Столбцов: {df.shape[1]}")
print("\nТип данных каждого поля:")
print(df.dtypes)
print("\nКоличество значений в каждом столбце:")
print(df.count())
print("\nШкала измерения каждого числового поля:")
numeric_cols = df.select_dtypes(include=['number']).columns
for col in numeric_cols:
    print(f"{col}: {df[col].min()} - {df[col].max()}")

Строк: 10000, Столбцов: 20

Тип данных каждого поля:
Id                 int64
DistrictId         int64
Rooms            float64
Square           float64
LifeSquare       float64
KitchenSquare    float64
Floor              int64
HouseFloor       float64
HouseYear          int64
Ecology_1        float64
Ecology_2         object
Ecology_3         object
Social_1           int64
Social_2           int64
Social_3           int64
Healthcare_1     float64
Helthcare_2        int64
Shops_1            int64
Shops_2           object
Price            float64
dtype: object

Количество значений в каждом столбце:
Id               10000
DistrictId       10000
Rooms            10000
Square           10000
LifeSquare        7887
KitchenSquare    10000
Floor            10000
HouseFloor       10000
HouseYear        10000
Ecology_1        10000
Ecology_2        10000
Ecology_3        10000
Social_1         10000
Social_2         10000
Social_3         10000
Healthcare_1      5202
Helthcare_2      10000
Sho

9. Удалите из таблицы столбцы, содержащие идентификаторы, переименуйте все оставшиеся названия колонок на русском языке.


10. Выведите отдельно столбец, содержащий цену, по номеру и названию. Выведите первую, десятую и предпоследнюю строку таблицы по номеру и по индексу.

11. Выделите в отдельную таблицу последние десять строк. Уберите в ней столбец с ценой. Склейте ее с первоначальной таблицей при помощи append. Заполните отсутствующие значения цены средним по таблице.

12. Выделите пять последних колонок в отдельную таблицу. Удалите в ней строки, в которых цена ниже среднего. Присоедините эту таблицу к изначальной (выберите самый подходящий тип соединения).